brace_style = "AlwaysNextLine"
fn_single_line = true
force_multiline_blocks = true
format_code_in_doc_comments = true
imports_granularity = "Crate"
imports_layout = "Vertical"
match_block_trailing_comma = true
max_width = 100
normalize_comments = true